services:
  shipment-service:
    image: base
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - ../shared:/shared
    networks:
      - sharednet

networks:
  sharednet:
    name: shared-network
    external: true
