global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # self scraping
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'showcase-service'
    static_configs:
      - targets: ['showcase-service:80']
