services:
  order-service:
    image: base
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ../shared:/shared
    ports:
      - 8002:8002
    networks:
      - sharednet

networks:
  sharednet:
    name: shared-network
    external: true

