#########################
#     Builder Stage     #
#########################

FROM golang:1.23.4-alpine3.19 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY main.go .
COPY pkg/ ./pkg

RUN go mod download
RUN go build -o build/app

#########################
#       App Stage       #
#########################

FROM alpine:latest AS app

COPY --from=builder /app/build /accountant

CMD ["./accountant/app"]